new css + user applications + search
Caveman21days/education pull request #20
Opened 2018-07-27 05:26 UTC by NaNisNumber

2018-07-27 05:30 UTC, Hardboy1208 commented on app/assets/javascripts/project.js
> +  const sendApplication = () => {
а зачем тут пустая функция?

2018-07-27 05:34 UTC, Hardboy1208 requested changes

2018-07-27 05:34 UTC, Hardboy1208 commented on app/controllers/users_controller.rb
> +<<<<<<< HEAD
Эй вы че - тут конфликты решать до конца надо и вот это гавно убирать!!!

2018-07-29 11:08 UTC, Caveman21days approved these changes

2018-07-29 11:08 UTC, Caveman21days commented on app/controllers/issues_controller.rb
> +    a_max_pidor = defined? @issuable.last_issue_date
Это чо за хренотень?

2018-07-29 11:08 UTC, merged